CogsLite3/Models/CardsViewModel.cs
using System.Collections.Generic;
using CogsLite.Core;

namespace CogsLite3.Models
{
    public class CardsViewModel
    {
		private readonly IEnumerable<Card> _cards;

		public CardsViewModel(IEnumerable<Card> cards)
		{
			_cards = cards;
		}

		public IEnumerable<Card> Cards => _cards;
    }
}

CogsLite3/Models/ErrorViewModel.cs
using System;

namespace CogsLite3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CogsLite3/Models/GamesViewModel.cs
using System.Collections.Generic;
using CogsLite.Core;

namespace CogsLite3.Models
{
    public class GamesViewModel
    {
		private readonly IEnumerable<Game> _games;

		public GamesViewModel(IEnumerable<Game> games)
		{
			_games = games;
		}

		public IEnumerable<Game> Games => _games;
    }
}

CogsLite3/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CogsLite.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CogsLite3.Controllers
{
    public class CardsController : Controller
    {
		private readonly IGameStore _gameStore;
		private readonly ICardStore _cardStore;
		private readonly IImageStore _imageStore;

		public CardsController(IGameStore gameStore, ICardStore cardStore, IImageStore imageStore)
		{
			_gameStore = gameStore ?? throw new ArgumentNullException(nameof(gameStore));
			_cardStore = cardStore ?? throw new ArgumentNullException(nameof(cardStore));
			_imageStore = imageStore ?? throw new ArgumentNullException(nameof(imageStore));
		}

        public IActionResult Index(Guid gameId)
        {
            return View();
        }

		public IActionResult Upload(Guid gameId)
		{
			var game = _gameStore.Get(gameId);
			ViewData["GameId"] = gameId;
			ViewData["GameName"] = game.Name;
			return View();
		}

		[HttpPost]
		public IActionResult Upload(Guid gameId, int cardsPerRow, int cardCount, IFormFile cardSheet)
		{			
			foreach(var imageData in ImageSlicer.Slice(cardsPerRow, cardCount, cardSheet.OpenReadStream()))
			{				
				var card = new Card
				{
					Id = Guid.NewGuid(),
					Name = String.Empty,
					GameId = gameId,
					CreatedOn = DateTime.Now
				};

				_cardStore.Add(card);
				_imageStore.Store(card.Id, imageData);
			}
			
			_gameStore.UpdateOne(gameId, g => g.CardCount += cardCount);
			return RedirectToAction("Cards", "Games", new { gameId });
		}

		public IActionResult Details(Guid cardId)
		{
			var card = _cardStore.Get(cardId);
			return View(card);
		}

		[HttpPost]
		public IActionResult UpdateDetails(Guid gameId, Guid cardId, string name)
		{
			_cardStore.UpdateOne(cardId, c => c.Name = name);
			return RedirectToAction("Cards", "Games", new { gameId });
		}
    }
}

CogsLite3/Controllers/GamesController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using CogsLite.Core;
using CogsLite3.Models;
using Microsoft.AspNetCore.Http;

namespace CogsLite3.Controllers
{
    public class GamesController : Controller
    {
		private readonly IGameStore _gameStore;
		private readonly ICardStore _cardStore;
		private readonly IImageStore _imageStore;

		public GamesController(IGameStore gameStore, ICardStore cardStore, IImageStore imageStore)
		{
			_gameStore = gameStore ?? throw new ArgumentNullException(nameof(gameStore));
			_imageStore = imageStore ?? throw new ArgumentNullException(nameof(imageStore));
			_cardStore = cardStore ?? throw new ArgumentNullException(nameof(cardStore));
		}

        public IActionResult Index()
        {
			var viewModel = new GamesViewModel(_gameStore.Get(String.Empty, 0, 15));
			return View(viewModel);
        }

		public IActionResult Cards(Guid gameId)
		{
			var game = _gameStore.Get(gameId);
			var viewModel = new CardsViewModel(_cardStore.Get(gameId, String.Empty, 0, 50));
			ViewData["GameId"] = game.Id;
			ViewData["GameName"] = game.Name;
			return View(viewModel);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(string name, IFormFile image)
		{
			var game = new Game
			{
				Id = Guid.NewGuid(),
				Name = name,
				CreatedOn = DateTime.Today
			};

			_gameStore.Add(game);

			if (image != null)
				_imageStore.Store(game.Id, image.OpenReadStream());

			return RedirectToAction("Index");
		}			
    }
}

CogsLite3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CogsLite3.Models;
using Microsoft.AspNetCore.Http;

namespace CogsLite3.Controllers
{
    public class HomeController : Controller
    {
		public HomeController()
		{
		}

        public IActionResult Index()
        {
			return View();
        }
        
        public IActionResult About()
        {
            return View();
        }

		public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CogsLite3/Controllers/ImagesController.cs
using System;
using CogsLite.Core;
using Microsoft.AspNetCore.Mvc;

namespace CogsLite3.Controllers
{
    public class ImagesController : Controller
    {
		private readonly IImageStore _imageStore;

		public ImagesController(IImageStore imageStore)
		{
			_imageStore = imageStore ?? throw new ArgumentNullException(nameof(imageStore));
		}
        public IActionResult Get(Guid id)
        {
			return new FileContentResult(_imageStore.Retrieve(id), "application/octet-stream");
        }
    }
}

CogsLite3/Controllers/LoginController.cs
using System;
using CogsLite.Core;
using Microsoft.AspNetCore.Mvc;

namespace CogsLite3.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserStore _userStore;

        public LoginController(IUserStore userStore)
        {
            _userStore = userStore ?? throw new ArgumentNullException(nameof(userStore));
        }

        public IActionResult Index(string message)
        {
            ViewData["Message"] = message;
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            var user = _userStore.Get(email);

            if (user != null && user.Password == password)
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("Index", new { message = "Unable to logon" });
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(string email, string displayName, string password)
        {
            User newUser = new User
            {
                EmailAddress = email,
                DisplayName = displayName,
                Password = password
            };
            _userStore.Add(newUser);
            return View();
        }
    }
}

CogsLite3/Views/Cards/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h2>Card Details</h2>
<div style="display: inline-block">
    <img src="@Url.Action("Get", "Images", new { id = Model.Id })"/>
</div>
<div style="display: inline-block">
    <form method="post" asp-action="UpdateDetails" asp-controller="Cards">
        <input type="hidden" name="gameId" value="@Model.GameId"/>
        <input type="hidden" name="cardId" value="@Model.Id"/>
        <div><input type="text" name="name" value="@Model.Name"/></div>
        <div><input type="submit" class="btn btn-primary" value="Update" /></div>
    </form>
</div>

CogsLite3/Views/Cards/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

<h2>@ViewData["GameName"] &gt; Upload cards</h2>
<form method="post" enctype="multipart/form-data" asp-controller="Cards" asp-action="Upload">
    <div class="form-group">
        <div class="col-md-10">
            <p>Cards per row:</p>
            <input type="number" name="cardsPerRow" />
        </div>
    </div>    
    <div class="form-group">
        <div class="col-md-10">
            <p>Number of cards:</p>
            <input type="number" name="cardCount" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload a card sheet</p>
            <input type="file" name="cardSheet"/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="hidden" name="gameId" value="@ViewData["GameId"]"/>
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>

CogsLite3/Views/Games/Cards.cshtml
@model CardsViewModel
@{
    ViewData["Title"] = "Cards";
}

<h2>@ViewData["GameName"] - Cards</h2>
<a href="@Url.Action("Upload", "Cards", new { gameId = ViewData["GameId"] })" class="btn btn-default">Upload cards</a>
<hr/>
<ul>
    @foreach (var card in Model.Cards)
    {
        <li class="card-item">
            <a href="@Url.Action("Details", "Cards", new { cardId = card.Id })">
                <img src="@Url.Action("Get", "Images", new { id = card.Id })" height="140" />
                <div>&nbsp;@card.Name</div>
            </a>
        </li>
    }
</ul>

CogsLite3/Views/Games/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<form method="post" enctype="multipart/form-data" asp-controller="Games" asp-action="Create">
    <h2>Create a new card game</h2>
    <p>Create a new card game entry, once created you can start adding cards and creating decks.</p>
    <div>Name</div>
    <div><input type="text" name="name" /></div>
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload a cover image for the game, this will be displayed in a card 6 x 4 aspect ratio. The card back for the game is a good choice.</p>
            <input type="file" name="image" />
        </div>
    </div>
    <div>
        <input type="submit" value="Create" />
    </div>
</form>

CogsLite3/Views/Games/Index.cshtml
@model GamesViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Explore card games</h2>
<a href="@Url.Action("Create", "Games")" class="btn btn-primary">New game</a>
<ul>
    @foreach(var game in Model.Games)
    {
        <li class="game-list-item">
            <img src="@Url.Action("Get", "Images", new { id = game.Id })" height="70"/>
            <a href="@Url.Action("Cards", "Games", new { gameId = game.Id })">@game.Name</a> 
        </li>
    }
</ul>

CogsLite3/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>Welcome to cogs lite, this tool will allow you to manage decks for tabletop simulator.</p>
<div>@Html.ActionLink("Upload a card sheet", "Upload", "Home")</div>
<div>@Html.ActionLink("View cards", "Cards", "Home")</div>

CogsLite3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<p>Welcome to cogs lite, a card and deck manager for table top simulator</p>

CogsLite3/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}

<h2>Upload</h2>
<form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="Upload">
    <div class="form-group">
        <div class="col-md-10">
            <p>Rows:</p>
            <input type="number" name="rows" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <p>Columns:</p>
            <input type="number" name="columns" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <p>Upload one or more files using this form:</p>
            <input type="file" name="files" multiple />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Upload" />
        </div>
    </div>
</form>

CogsLite3/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Login</h2>
<br/>
<form method="post" asp-controller="Login" asp-action="Login">
    <div class="container">
        <div style="color: darkred">@ViewData["Message"]</div>
    <label for="email"><b>Email</b></label>
    <input type="text" name="email" required>
    <br />
    <label for="password"><b>Password</b></label>
    <input type="password" name="password" required>
    <br />
    <button type="submit">Login</button>
    <br />
    <a class="signup-prompt" href="@Url.Action("SignUp", "Login")">Not got a CogsLite account? Sign up</a>
    </div>
</form>

CogsLite3/Views/Login/SignUp.cshtml
@{
    ViewData["Title"] = "SignUp";
}

<h2>Sign Up</h2>

<br />
<form method="post" asp-controller="Login" asp-action="SignUp">
    <div class="container">
        <label for="displayName"><b>Display name</b></label>
        <input type="text" name="displayName" required>
        <br />
        <label for="email"><b>Email</b></label>
        <input type="text" name="email" required>
        <br />
        <label for="password"><b>Password</b></label>
        <input type="password" name="password" required>
        <br />
        <button type="submit">Submit</button>
    </div>
</form>

CogsLite3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CogsLite3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CogsLite3</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Games" asp-action="Index">Games</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CogsLite3</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>